"""Synthetic multi-week learner histories for Human Gate 6.

    python -m app.learning.history_report > docs/human-gates/gate-6-histories.md

Each row shows the evidence inputs, the effective score and weight the model derives, and the
resulting state after that evidence, so reviewers can check every step of the calculation.
"""

from __future__ import annotations

from dataclasses import replace
from datetime import UTC, datetime, timedelta

from app.learning.model import (
    LEARNING_RATE,
    MAX_STEP,
    PRIOR_MASTERY,
    Evidence,
    compute_state,
    effective_score,
    evidence_weight,
)

T0 = datetime(2026, 9, 1, 9, tzinfo=UTC)


def ev(
    day: float,
    score: float,
    kind: str,
    hint: int = 0,
    low_confidence: bool = False,
    **flags: bool,
) -> Evidence:
    return Evidence(
        occurred_at=T0 + timedelta(days=day),
        score=score,
        confidence=0.35 if low_confidence else 0.8,
        hint_level=hint,
        exercise_type=kind,
        **flags,
    )


HISTORIES: list[tuple[str, str, str, list[Evidence]]] = [
    (
        "Steady improver (sliding-window invariant)",
        "sliding-window.invariant",
        "reasoning",
        [
            ev(0, 0.2, "interview", hint=3),
            ev(1, 0.5, "explain"),
            ev(4, 0.8, "trace"),
            ev(8, 1.0, "implementation"),
            ev(15, 1.0, "transfer", transfer=True),
            ev(35, 1.0, "interview"),
        ],
    ),
    (
        "Contradictory evidence (binary-search boundaries)",
        "binary-search.boundaries",
        "debugging",
        [
            ev(0, 1.0, "interview"),
            ev(2, 0.1, "debug"),
            ev(3, 0.9, "debug"),
            ev(6, 0.2, "implementation", hint=2),
            ev(12, 0.9, "implementation"),
        ],
    ),
    (
        "Solution viewer (arrays-hashing transfer)",
        "arrays-hashing.transfer",
        "transfer",
        [
            ev(0, 0.0, "interview"),
            ev(0.1, 1.0, "key_insight", assisted=True),
            ev(1, 1.0, "pseudocode", assisted=True),
            ev(4, 1.0, "implementation", assisted=True, repeat_exposure=True),
            ev(12, 1.0, "transfer", transfer=True),
        ],
    ),
    (
        "Repeated same problem (stack recognition)",
        "stack.recognition",
        "recognition",
        [
            ev(0, 1.0, "interview"),
            ev(1, 1.0, "interview", repeat_exposure=True),
            ev(2, 1.0, "interview", repeat_exposure=True),
            ev(3, 1.0, "interview", repeat_exposure=True),
            ev(4, 1.0, "interview", repeat_exposure=True),
        ],
    ),
    (
        "Low-confidence diagnoses then a clean mock (trees complexity)",
        "trees.complexity",
        "complexity",
        [
            ev(0, 0.2, "interview", low_confidence=True),
            ev(3, 0.3, "recall", low_confidence=True),
            ev(10, 1.0, "recall"),
            ev(20, 1.0, "mock_interview"),
        ],
    ),
]


def render() -> str:
    lines = [
        "# Human Gate 6 — Synthetic learner histories",
        "",
        f"Generated by `python -m app.learning.history_report` (prior {PRIOR_MASTERY}, learning "
        f"rate {LEARNING_RATE}, max step ±{MAX_STEP}). Mastery values are internal; learners only "
        "see the band and explanation.",
        "",
    ]
    for title, slug, capability_type, items in HISTORIES:
        lines += [f"## {title}", "", f"Capability `{slug}` (type `{capability_type}`).", ""]
        lines.append(
            "| Day | Evidence | Score | Hint | Flags | Effective | Weight | Mastery | Band | "
            "Next review (days) | Explanation |"
        )
        lines.append("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |")
        previous: datetime | None = None
        for index, item in enumerate(items):
            gap = (item.occurred_at - previous).total_seconds() / 86400 if previous else None
            state = compute_state(items[: index + 1], capability_type)
            flags = ", ".join(
                name
                for name, on in (
                    ("assisted", item.assisted),
                    ("transfer", item.transfer),
                    ("repeat", item.repeat_exposure),
                    ("low confidence", item.confidence < 0.5),
                )
                if on
            )
            day = (item.occurred_at - T0).total_seconds() / 86400
            lines.append(
                f"| {day:g} | {item.exercise_type} | {item.score:.2f} | {item.hint_level} | "
                f"{flags or '—'} | {effective_score(item):.2f} | "
                f"{evidence_weight(replace(item), gap):.2f} | {state.mastery:.2f} | {state.band} | "
                f"{state.stability_days:g} | {state.explanation} |"
            )
            previous = item.occurred_at
        lines.append("")
    lines += [
        "## Questions for the reviewer",
        "",
        "1. Are any jumps surprising (single-step changes are capped at ±0.25)?",
        "2. Does repeated success on the same problem stay below Strong (it should)?",
        "3. Does solution-assisted work avoid inflating transfer (it should stay ≤ Developing "
        "until an independent transfer success)?",
        "4. Are the explanations understandable without seeing the numbers?",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    print(render())
