"""learning loop: interviews, evaluation, evidence, scheduling, drills, solution views

Rollout note: additive except review_attempts.exercise_id becoming nullable; downgrade
deletes problem-level review attempts (exercise_id IS NULL) before restoring NOT NULL.

Revision ID: 20260924_0004
Revises: 20260924_0003
Create Date: 2026-09-24 19:08:42.400385
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260924_0004"
down_revision: str | None = "20260924_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analytics_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_analytics_events_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_analytics_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "drill_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("budget_minutes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("current_index", sa.Integer(), nullable=False),
        sa.Column("planned_minutes", sa.Float(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'completed', 'abandoned')", name="ck_drill_status"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("drill_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_drill_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "capability_evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("capability_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("problem_id", sa.String(length=36), nullable=True),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("hint_level", sa.Integer(), nullable=False),
        sa.Column("exercise_type", sa.String(length=32), nullable=False),
        sa.Column("assisted", sa.Boolean(), nullable=False),
        sa.Column("transfer", sa.Boolean(), nullable=False),
        sa.Column("repeat_exposure", sa.Boolean(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("excluded", sa.Boolean(), nullable=False),
        sa.Column("excluded_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_evidence_confidence"),
        sa.CheckConstraint("score >= 0 AND score <= 1", name="ck_evidence_score"),
        sa.ForeignKeyConstraint(["capability_id"], ["capabilities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "dedupe_key", name="uq_evidence_dedupe"),
    )
    with op.batch_alter_table("capability_evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_capability_evidence_capability_id"), ["capability_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_capability_evidence_problem_id"), ["problem_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_capability_evidence_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_capability_evidence_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            "ix_evidence_user_capability_time",
            ["user_id", "capability_id", "occurred_at"],
            unique=False,
        )

    op.create_table(
        "interview_evaluations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("evaluator", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("event_seq_from", sa.Integer(), nullable=False),
        sa.Column("event_seq_to", sa.Integer(), nullable=False),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.Column("validation", sa.JSON(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("fallback_used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('completed', 'degraded', 'failed')", name="ck_evaluation_status"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("interview_evaluations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_interview_evaluations_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_interview_evaluations_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "llm_calls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("task", sa.String(length=40), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_llm_calls_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_calls_user_id"), ["user_id"], unique=False)

    op.create_table(
        "review_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("capability_id", sa.String(length=36), nullable=False),
        sa.Column("exercise_id", sa.String(length=36), nullable=True),
        sa.Column("problem_id", sa.String(length=36), nullable=True),
        sa.Column("task_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("snoozed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("chain_id", sa.String(length=36), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'snoozed', 'skipped', 'completed', 'invalidated', 'superseded')",
            name="ck_task_status",
        ),
        sa.ForeignKeyConstraint(["capability_id"], ["capabilities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_review_tasks_capability_id"), ["capability_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_review_tasks_chain_id"), ["chain_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_review_tasks_exercise_id"), ["exercise_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_review_tasks_problem_id"), ["problem_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_review_tasks_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_tasks_user_status_due", ["user_id", "status", "due_at"], unique=False
        )
        batch_op.create_index(
            "uq_tasks_active_dedupe",
            ["user_id", "dedupe_key"],
            unique=True,
            postgresql_where=sa.text("status IN ('pending', 'snoozed')"),
            sqlite_where=sa.text("status IN ('pending', 'snoozed')"),
        )

    op.create_table(
        "solution_views",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("problem_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("viewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("context", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("solution_views", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_solution_views_problem_id"), ["problem_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_solution_views_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_solution_views_user_id"), ["user_id"], unique=False)

    op.create_table(
        "diagnosis_flags",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("evaluation_id", sa.String(length=36), nullable=False),
        sa.Column("capability_slug", sa.String(length=160), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_id"], ["interview_evaluations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("diagnosis_flags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_diagnosis_flags_evaluation_id"), ["evaluation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_diagnosis_flags_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("hint_logs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("capability_tags", sa.JSON(), nullable=False, server_default="[]")
        )
        batch_op.add_column(sa.Column("review_attempt_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_hint_logs_review_attempt_id"), ["review_attempt_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_hint_logs_review_attempt_id",
            "review_attempts",
            ["review_attempt_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("interview_events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("actor", sa.String(length=20), nullable=False, server_default="system")
        )
        batch_op.add_column(
            sa.Column("client_timestamp", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("idempotency_key", sa.String(length=80), nullable=True))
        batch_op.create_unique_constraint("uq_event_idempotency", ["session_id", "idempotency_key"])

    with op.batch_alter_table("interview_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version", sa.Integer(), nullable=False, server_default="1"))
        batch_op.add_column(
            sa.Column("event_count", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(sa.Column("policy", sa.JSON(), nullable=False, server_default="{}"))
        batch_op.add_column(
            sa.Column("problem_version", sa.Integer(), nullable=False, server_default="1")
        )
        batch_op.add_column(
            sa.Column("hints_used", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column("max_hint_level", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(sa.Column("current_code", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("time_limit_s", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("solution_viewed_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("accommodations", sa.JSON(), nullable=False, server_default="{}")
        )

    with op.batch_alter_table("learner_capability_states", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("band", sa.String(length=20), nullable=False, server_default="Weak")
        )
        batch_op.add_column(sa.Column("confidence", sa.Float(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("explanation", sa.Text(), nullable=False, server_default=""))

    with op.batch_alter_table("review_attempts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("problem_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("task_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("drill_session_id", sa.String(length=36), nullable=True))
        batch_op.add_column(
            sa.Column("mode", sa.String(length=20), nullable=False, server_default="retrieve")
        )
        batch_op.add_column(
            sa.Column("status", sa.String(length=20), nullable=False, server_default="in_progress")
        )
        batch_op.add_column(sa.Column("latency_ms", sa.Integer(), nullable=True))
        batch_op.alter_column("exercise_id", existing_type=sa.VARCHAR(length=36), nullable=True)
        batch_op.create_index(
            batch_op.f("ix_review_attempts_drill_session_id"), ["drill_session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_review_attempts_problem_id"), ["problem_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_review_attempts_task_id"), ["task_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_review_attempts_problem_id", "problems", ["problem_id"], ["id"], ondelete="SET NULL"
        )
        batch_op.create_foreign_key(
            "fk_review_attempts_drill_session_id",
            "drill_sessions",
            ["drill_session_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "fk_review_attempts_task_id", "review_tasks", ["task_id"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("timezone", sa.String(length=64), nullable=False, server_default="UTC")
        )
        batch_op.add_column(
            sa.Column("daily_review_cap", sa.Integer(), nullable=False, server_default="12")
        )
        batch_op.add_column(
            sa.Column("preferences", sa.JSON(), nullable=False, server_default="{}")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("preferences")
        batch_op.drop_column("daily_review_cap")
        batch_op.drop_column("timezone")

    op.execute("DELETE FROM review_attempts WHERE exercise_id IS NULL")
    with op.batch_alter_table("review_attempts", schema=None) as batch_op:
        batch_op.drop_constraint("fk_review_attempts_task_id", type_="foreignkey")
        batch_op.drop_constraint("fk_review_attempts_drill_session_id", type_="foreignkey")
        batch_op.drop_constraint("fk_review_attempts_problem_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_review_attempts_task_id"))
        batch_op.drop_index(batch_op.f("ix_review_attempts_problem_id"))
        batch_op.drop_index(batch_op.f("ix_review_attempts_drill_session_id"))
        batch_op.alter_column("exercise_id", existing_type=sa.VARCHAR(length=36), nullable=False)
        batch_op.drop_column("latency_ms")
        batch_op.drop_column("status")
        batch_op.drop_column("mode")
        batch_op.drop_column("drill_session_id")
        batch_op.drop_column("task_id")
        batch_op.drop_column("problem_id")

    with op.batch_alter_table("learner_capability_states", schema=None) as batch_op:
        batch_op.drop_column("explanation")
        batch_op.drop_column("confidence")
        batch_op.drop_column("band")

    with op.batch_alter_table("interview_sessions", schema=None) as batch_op:
        batch_op.drop_column("accommodations")
        batch_op.drop_column("solution_viewed_at")
        batch_op.drop_column("last_activity_at")
        batch_op.drop_column("deadline_at")
        batch_op.drop_column("time_limit_s")
        batch_op.drop_column("current_code")
        batch_op.drop_column("max_hint_level")
        batch_op.drop_column("hints_used")
        batch_op.drop_column("problem_version")
        batch_op.drop_column("policy")
        batch_op.drop_column("event_count")
        batch_op.drop_column("version")

    with op.batch_alter_table("interview_events", schema=None) as batch_op:
        batch_op.drop_constraint("uq_event_idempotency", type_="unique")
        batch_op.drop_column("idempotency_key")
        batch_op.drop_column("client_timestamp")
        batch_op.drop_column("actor")

    with op.batch_alter_table("hint_logs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_hint_logs_review_attempt_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_hint_logs_review_attempt_id"))
        batch_op.drop_column("review_attempt_id")
        batch_op.drop_column("capability_tags")

    with op.batch_alter_table("diagnosis_flags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_diagnosis_flags_user_id"))
        batch_op.drop_index(batch_op.f("ix_diagnosis_flags_evaluation_id"))

    op.drop_table("diagnosis_flags")
    with op.batch_alter_table("solution_views", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_solution_views_user_id"))
        batch_op.drop_index(batch_op.f("ix_solution_views_session_id"))
        batch_op.drop_index(batch_op.f("ix_solution_views_problem_id"))

    op.drop_table("solution_views")
    with op.batch_alter_table("review_tasks", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_tasks_active_dedupe",
            postgresql_where=sa.text("status IN ('pending', 'snoozed')"),
            sqlite_where=sa.text("status IN ('pending', 'snoozed')"),
        )
        batch_op.drop_index("ix_tasks_user_status_due")
        batch_op.drop_index(batch_op.f("ix_review_tasks_user_id"))
        batch_op.drop_index(batch_op.f("ix_review_tasks_problem_id"))
        batch_op.drop_index(batch_op.f("ix_review_tasks_exercise_id"))
        batch_op.drop_index(batch_op.f("ix_review_tasks_chain_id"))
        batch_op.drop_index(batch_op.f("ix_review_tasks_capability_id"))

    op.drop_table("review_tasks")
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_calls_user_id"))
        batch_op.drop_index(batch_op.f("ix_llm_calls_session_id"))

    op.drop_table("llm_calls")
    with op.batch_alter_table("interview_evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interview_evaluations_user_id"))
        batch_op.drop_index(batch_op.f("ix_interview_evaluations_session_id"))

    op.drop_table("interview_evaluations")
    with op.batch_alter_table("capability_evidence", schema=None) as batch_op:
        batch_op.drop_index("ix_evidence_user_capability_time")
        batch_op.drop_index(batch_op.f("ix_capability_evidence_user_id"))
        batch_op.drop_index(batch_op.f("ix_capability_evidence_source_id"))
        batch_op.drop_index(batch_op.f("ix_capability_evidence_problem_id"))
        batch_op.drop_index(batch_op.f("ix_capability_evidence_capability_id"))

    op.drop_table("capability_evidence")
    with op.batch_alter_table("drill_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_drill_sessions_user_id"))

    op.drop_table("drill_sessions")
    with op.batch_alter_table("analytics_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analytics_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_analytics_events_name"))

    op.drop_table("analytics_events")
    # ### end Alembic commands ###
